In [1]:
import torch

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.item()

7

In [6]:
scalar.ndim

0

In [8]:
MATRIX = torch.tensor([[7, 8], [9, 10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [17]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
tensor.shape

torch.Size([3, 3])

In [18]:
random_tensor = torch.rand(5, 6)
random_tensor

tensor([[0.2147, 0.8589, 0.8897, 0.9058, 0.1189, 0.6439],
        [0.6691, 0.5319, 0.6334, 0.1381, 0.2192, 0.3879],
        [0.1449, 0.3579, 0.8954, 0.2149, 0.8340, 0.5383],
        [0.9545, 0.8720, 0.3863, 0.3954, 0.2543, 0.9039],
        [0.4427, 0.2497, 0.2305, 0.3642, 0.5411, 0.8394]])

In [20]:
zeros = torch.zeros(5,6)
zeros

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [22]:
ones = torch.ones(6,7)
ones

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])

In [25]:
range_tensor = torch.arange(start=0, end=7, step=1.2)
range_tensor

tensor([0.0000, 1.2000, 2.4000, 3.6000, 4.8000, 6.0000])

In [26]:
zeros_like = torch.zeros_like(range_tensor)
zeros_like

tensor([0., 0., 0., 0., 0., 0.])

In [30]:
float32_tensor = torch.tensor([1.0, 2, 3], dtype=None)
float32_tensor.dtype

torch.float32

In [32]:
float16_tensor = float32_tensor.type(torch.float16)
float16_tensor.dtype

torch.float16

In [33]:
float16_tensor.device

device(type='cpu')

In [36]:
tensor = torch.tensor([1, 2, 3])

tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [38]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Matrix Multiplication
# matmul

tensor = torch.tensor([1, 2, 3])

# Element Wise Multiplication
tensor*tensor

tensor([1, 4, 9])

In [40]:
# Matrix Multiplication

torch.matmul(tensor, tensor)

tensor(14)

In [41]:
tensor = torch.tensor([[1, 2, 3], [2, 3, 4]])

In [42]:
torch.matmul(tensor, tensor)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [43]:
torch.matmul(tensor, tensor.T)

tensor([[14, 20],
        [20, 29]])

In [44]:
tensor = torch.arange(0, 10, 1.34)
tensor

tensor([0.0000, 1.3400, 2.6800, 4.0200, 5.3600, 6.7000, 8.0400, 9.3800])

In [46]:
tensor.min(), tensor.max(), tensor.sum()

(tensor(0.), tensor(9.3800), tensor(37.5200))

In [47]:
tensor.mean()

tensor(4.6900)

In [54]:
tensor = torch.arange(0, 10, 1)
# tensor.mean() # Error

tensor = tensor.type(dtype=torch.float32)
tensor.mean()

tensor(4.5000)

In [55]:
tensor.argmax()

tensor(9)

In [56]:
tensor.argmin()

tensor(0)

In [59]:
x = torch.arange(1., 10.)

x_reshape_view = x.view(3,3)

x, x_reshape_view

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]))

In [61]:
x.reshape(3,3), x

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [62]:
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [65]:
# ?y = torch.tensor([x, x, x]) # Error
y = torch.stack([x, x, x])
y

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [68]:
x = torch.rand(224, 244, 3)
x

tensor([[[0.7822, 0.2002, 0.9914],
         [0.9708, 0.0762, 0.8030],
         [0.8266, 0.8080, 0.7887],
         ...,
         [0.5029, 0.1466, 0.1636],
         [0.1972, 0.9417, 0.2578],
         [0.0326, 0.8080, 0.6227]],

        [[0.1984, 0.9371, 0.5322],
         [0.5316, 0.0089, 0.7339],
         [0.9079, 0.2277, 0.4269],
         ...,
         [0.5093, 0.7359, 0.1806],
         [0.9530, 0.4296, 0.9563],
         [0.4273, 0.3615, 0.0715]],

        [[0.9195, 0.7781, 0.0610],
         [0.6799, 0.4936, 0.3258],
         [0.7445, 0.1823, 0.4529],
         ...,
         [0.0962, 0.0707, 0.7378],
         [0.3667, 0.2441, 0.7438],
         [0.5540, 0.7840, 0.6054]],

        ...,

        [[0.8095, 0.2235, 0.6817],
         [0.0181, 0.5947, 0.8917],
         [0.6776, 0.0791, 0.6450],
         ...,
         [0.1110, 0.7282, 0.0655],
         [0.4286, 0.7855, 0.7191],
         [0.9022, 0.6474, 0.7556]],

        [[0.3316, 0.1645, 0.2187],
         [0.8613, 0.2427, 0.0558],
         [0.

In [70]:
x_new = x.permute(1,2,0)
x_new

tensor([[[0.7822, 0.1984, 0.9195,  ..., 0.8095, 0.3316, 0.2249],
         [0.2002, 0.9371, 0.7781,  ..., 0.2235, 0.1645, 0.7645],
         [0.9914, 0.5322, 0.0610,  ..., 0.6817, 0.2187, 0.0423]],

        [[0.9708, 0.5316, 0.6799,  ..., 0.0181, 0.8613, 0.4370],
         [0.0762, 0.0089, 0.4936,  ..., 0.5947, 0.2427, 0.5858],
         [0.8030, 0.7339, 0.3258,  ..., 0.8917, 0.0558, 0.9504]],

        [[0.8266, 0.9079, 0.7445,  ..., 0.6776, 0.3766, 0.4288],
         [0.8080, 0.2277, 0.1823,  ..., 0.0791, 0.0158, 0.8289],
         [0.7887, 0.4269, 0.4529,  ..., 0.6450, 0.3096, 0.3984]],

        ...,

        [[0.5029, 0.5093, 0.0962,  ..., 0.1110, 0.0582, 0.5015],
         [0.1466, 0.7359, 0.0707,  ..., 0.7282, 0.3420, 0.4640],
         [0.1636, 0.1806, 0.7378,  ..., 0.0655, 0.6910, 0.4613]],

        [[0.1972, 0.9530, 0.3667,  ..., 0.4286, 0.9230, 0.5946],
         [0.9417, 0.4296, 0.2441,  ..., 0.7855, 0.8573, 0.4106],
         [0.2578, 0.9563, 0.7438,  ..., 0.7191, 0.5951, 0.2613]],

 

In [71]:
x = torch.rand(1, 2, 1, 5)

In [77]:
x_new = x.squeeze()
x_new.shape

torch.Size([2, 5])

In [81]:
x_new.unsqueeze(dim=1).shape

torch.Size([2, 1, 5])

In [82]:
x_new

tensor([[0.4132, 0.2646, 0.4789, 0.6656, 0.8479],
        [0.9209, 0.4244, 0.8654, 0.0502, 0.0269]])

In [83]:
x_new[0]

tensor([0.4132, 0.2646, 0.4789, 0.6656, 0.8479])

In [86]:
tensor = torch.rand(244, 2, 3)

In [91]:
tensor[243]

tensor([[0.2733, 0.7692, 0.6450],
        [0.9993, 0.5260, 0.8730]])

In [98]:
tensor[0, 1]

tensor([0.8372, 0.6701, 0.1663])

In [99]:
tensor[:, 1]

tensor([[8.3719e-01, 6.7014e-01, 1.6627e-01],
        [7.4982e-01, 5.8716e-01, 1.8521e-01],
        [8.9985e-01, 9.7988e-01, 9.6187e-01],
        [5.3488e-01, 9.2014e-01, 4.2476e-01],
        [5.3219e-01, 2.8728e-01, 9.0336e-01],
        [4.3397e-02, 7.9705e-01, 6.5011e-01],
        [7.0943e-01, 8.2157e-01, 6.3904e-01],
        [5.8551e-01, 3.0196e-01, 8.8059e-01],
        [9.8568e-01, 8.4588e-01, 8.5635e-01],
        [7.7500e-01, 4.8707e-01, 2.4202e-01],
        [9.3766e-01, 9.8891e-01, 9.7752e-01],
        [2.2332e-01, 3.1712e-01, 3.5344e-01],
        [4.3504e-02, 6.2165e-01, 3.6704e-01],
        [2.8073e-01, 3.6976e-01, 3.2974e-01],
        [2.6521e-01, 6.4211e-01, 9.4909e-01],
        [9.1556e-01, 9.9987e-01, 2.7750e-01],
        [4.3379e-01, 1.9422e-01, 4.1571e-01],
        [4.9121e-01, 3.5544e-02, 3.7484e-01],
        [5.9987e-01, 7.4905e-01, 9.1803e-01],
        [5.9308e-01, 7.2855e-01, 7.6487e-01],
        [2.2171e-01, 6.9309e-01, 3.5491e-01],
        [6.8461e-01, 7.3756e-01, 5

In [100]:
import numpy as np

In [110]:
array = np.arange(1., 9.)
array, array.dtype

(array([1., 2., 3., 4., 5., 6., 7., 8.]), dtype('float64'))

In [111]:
tensor = torch.from_numpy(array)
tensor, tensor.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64), torch.float64)

In [115]:
x = torch.ones(7)
x, x.dtype, x.device

(tensor([1., 1., 1., 1., 1., 1., 1.]), torch.float32, device(type='cpu'))

In [117]:
numpy_tensor = x.numpy()
numpy_tensor, numpy_tensor.dtype

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32), dtype('float32'))

In [128]:
# Random Seed

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)

ra = torch.rand(3, 4)
ra


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [131]:
torch.manual_seed(RANDOM_SEED)
rb = torch.rand(3, 4)


rb, ra, print(rb == ra)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 None)

In [127]:
RANDOM_SEED = 42

# Set the seed for the CPU
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3, 4)

# To create another random tensor with the same values, you must reset the seed
torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A == random_tensor_B) # Will be all True
print(random_tensor_A)
print(random_tensor_B)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
